<?php

/**
 * @file
 * Contains views_globalhtml.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_globalhtml_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_globalhtml module.
    case 'help.page.views_globalhtml':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views Handler Global Html Area') . '</p>';
      return $output;

    default:
  }
}
